n1, n2, n3, n4 = int(input()), int(input()), int(input()), int(input())
print("|{:5} {:5}|".format(n1,n2))
print("|{:5} {:5}|".format(n3,n4))
print("|{:<5} {:<5}|".format(n1,n2))
print("|{:<5} {:<5}|".format(n3,n4))