file = input()
original = input()
replace = input()
file = open("Practice/3/" + file, "r+", encoding="utf-8")
original_content = file.read()
new_content = original_content.replace(original, replace)
file.seek(0)
file.write(new_content)
file.close()
print("=== Before the replacement\n" + original_content)
print("=== After the replacement\n" + new_content)